name: gps_mobile
description: "A new Flutter project for GPS Tracking (Light Version)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  flutter_map: ^6.1.0 # Alternative map if preferred
  socket_io_client: ^2.0.3 # For live data
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
